<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{6326f650-afd1-4789-988e-75eb7cdbc535}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
{attribute 'pytmc' := '
        pv: PLC:113:TEST
'}
fbCoeRead : FB_Read70x1CoeData;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbCoeRead(userNetId:='172.21.148.67.2.1');]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>